import type { Metadata } from "next";
import { Quicksand } from "next/font/google"; // Import Quicksand font
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

// Define Quicksand font
const quicksand = Quicksand({
  subsets: ["latin"], // Include specific subsets
  weight: ["400", "500", "600", "700"], // Choose font weights
});

export const metadata: Metadata = {
  title: {
    template: "Local Marketplace - %s",
    default: "Local Artisan - Marketplace",
  },
  description: "Generated by create next app",
  applicationName: "Local Artisan Marketplace",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={quicksand.className}>
      <body className="font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
